In [ ]:
import pathlib

import polars as pl
from mcr_py.utils.geometa import GeoMeta
from mcr_py.utils.logger import setup

setup("INFO")

In [2]:
city_name = "cologne"
date = "20250718"

In [3]:
data_directory = pathlib.Path("../data/")
base_directory = data_directory / date
cache_path = base_directory / "cache/"
osm_path = base_directory / "osm_raw"
geometa_path = base_directory / f"cache/{city_name}_geometa.pkl"
mcr5_output_path = base_directory / f"mcr5_results/{city_name}"
profiles_tariffs_path = mcr5_output_path / "profiles_tariffs.parquet"
profiles_categories_path = mcr5_output_path / "profiles_categories_tariffs.parquet"

geo_meta = GeoMeta.load(geometa_path)

In [4]:
profiles_tariffs = pl.read_parquet(profiles_tariffs_path)

In [5]:
profiles_tariffs.filter(pl.col("optimal") == 0)

shape: (2_476, 10)
┌────────────┬────────────┬───────────┬─────────┬───┬────────────┬────────────┬───────────┬────────┐
│ hex_id     ┆ any_column ┆ all_costs ┆ optimal ┆ … ┆ core_scena ┆ required_c ┆ optimal_i ┆ cost_0 │
│ ---        ┆ _different ┆ ---       ┆ ---     ┆   ┆ rio        ┆ ost_for_op ┆ n_minutes ┆ ---    │
│ str        ┆ ---        ┆ list[f64] ┆ f64     ┆   ┆ ---        ┆ timal_in_e ┆ ---       ┆ f64    │
│            ┆ bool       ┆           ┆         ┆   ┆ str        ┆ …          ┆ f64       ┆        │
│            ┆            ┆           ┆         ┆   ┆            ┆ ---        ┆           ┆        │
│            ┆            ┆           ┆         ┆   ┆            ┆ f64        ┆           ┆        │
╞════════════╪════════════╪═══════════╪═════════╪═══╪════════════╪════════════╪═══════════╪════════╡
│ 881fa110ab ┆ false      ┆ [0.0]     ┆ 0.0     ┆ … ┆ walking    ┆ 0.0        ┆ 0.0       ┆ 0.0    │
│ fffff      ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆        │
│ 881fa1d19b ┆ false      ┆ [0.0]     ┆ 0.0     ┆ … ┆ walking    ┆ 0.0        ┆ 0.0       ┆ 0.0    │
│ fffff      ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆        │
│ 881fa564dd ┆ false      ┆ [0.0]     ┆ 0.0     ┆ … ┆ walking    ┆ 0.0        ┆ 0.0       ┆ 0.0    │
│ fffff      ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆        │
│ 881fa18f5d ┆ false      ┆ [0.0]     ┆ 0.0     ┆ … ┆ walking    ┆ 0.0        ┆ 0.0       ┆ 0.0    │
│ fffff      ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆        │
│ 881fa1d647 ┆ false      ┆ [0.0]     ┆ 0.0     ┆ … ┆ walking    ┆ 0.0        ┆ 0.0       ┆ 0.0    │
│ fffff      ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆        │
│ …          ┆ …          ┆ …         ┆ …       ┆ … ┆ …          ┆ …          ┆ …         ┆ …      │
│ 881fa1943b ┆ false      ┆ [0.0]     ┆ 0.0     ┆ … ┆ walking    ┆ 0.0        ┆ 0.0       ┆ 0.0    │
│ fffff      ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆        │
│ 881fa1c6a5 ┆ false      ┆ [0.0]     ┆ 0.0     ┆ … ┆ walking    ┆ 0.0        ┆ 0.0       ┆ 0.0    │
│ fffff      ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆        │
│ 881fa11097 ┆ false      ┆ [0.0]     ┆ 0.0     ┆ … ┆ walking    ┆ 0.0        ┆ 0.0       ┆ 0.0    │
│ fffff      ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆        │
│ 881fa1916b ┆ false      ┆ [0.0]     ┆ 0.0     ┆ … ┆ walking    ┆ 0.0        ┆ 0.0       ┆ 0.0    │
│ fffff      ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆        │
│ 881fa110e9 ┆ false      ┆ [0.0]     ┆ 0.0     ┆ … ┆ walking    ┆ 0.0        ┆ 0.0       ┆ 0.0    │
│ fffff      ┆            ┆           ┆         ┆   ┆            ┆            ┆           ┆        │
└────────────┴────────────┴───────────┴─────────┴───┴────────────┴────────────┴───────────┴────────┘

In [6]:
pl.read_ipc(mcr5_output_path / "walking" / "881fa110abfffff.feather")

Could not memory_map compressed IPC file, defaulting to normal read. Toggle off 'memory_map' to silence this warning.

shape: (306_461, 5)
┌─────────────┬───────┬──────┬─────────────┬─────────────────────┐
│ osm_node_id ┆ time  ┆ cost ┆ n_transfers ┆ human_readable_time │
│ ---         ┆ ---   ┆ ---  ┆ ---         ┆ ---                 │
│ i64         ┆ i64   ┆ i64  ┆ i64         ┆ str                 │
╞═════════════╪═══════╪══════╪═════════════╪═════════════════════╡
│ 1737721386  ┆ 28800 ┆ 0    ┆ 0           ┆ 08:00:00            │
│ 7956286831  ┆ 28800 ┆ 0    ┆ 0           ┆ 08:00:00            │
│ 7905623350  ┆ 28800 ┆ 0    ┆ 0           ┆ 08:00:00            │
│ 1436208884  ┆ 28800 ┆ 0    ┆ 0           ┆ 08:00:00            │
│ 2049698342  ┆ 28800 ┆ 0    ┆ 0           ┆ 08:00:00            │
│ …           ┆ …     ┆ …    ┆ …           ┆ …                   │
│ 1448466270  ┆ 28800 ┆ 0    ┆ 0           ┆ 08:00:00            │
│ 3810467062  ┆ 28800 ┆ 0    ┆ 0           ┆ 08:00:00            │
│ 8367133340  ┆ 28800 ┆ 0    ┆ 0           ┆ 08:00:00            │
│ 988695680   ┆ 28800 ┆ 0    ┆ 0           ┆ 08:00:00            │
│ 708691847   ┆ 28800 ┆ 0    ┆ 0           ┆ 08:00:00            │
└─────────────┴───────┴──────┴─────────────┴─────────────────────┘