In [1]:
import logging
import pathlib

import mcr_py.helper_functions
import mcr_py.mcr5.labels
import mcr_py.minute_city.minute_city
import polars as pl
from mcr_py.utils.logger import setup

setup("INFO")

In [2]:
city_name = "cologne"
date = "20250926"

In [3]:
data_directory = pathlib.Path("../data/")
base_directory = data_directory / date
cache_path = base_directory / "cache/"
osm_path = base_directory / "osm_raw"
geometa_path = base_directory / f"cache/{city_name}_geometa.pkl"
mcr5_output_path = base_directory / f"mcr5_results/{city_name}"
geo_meta, geo_data = mcr_py.helper_functions.load_auxiliary_classes(
    geo_meta_path=geometa_path,
    city_id="Koeln",
    osm_path=osm_path,
    cache_path=cache_path,
)

[14:49:35] INFO     Loading OSM walking                               ]8;id=446299;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py\data.py]8;;\:]8;id=768094;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py#62\62]8;;\
[14:49:38] INFO     Loading OSM walking done (2.64 seconds)           ]8;id=256656;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py\data.py]8;;\:]8;id=885564;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py#62\62]8;;\
           INFO     Loading OSM POIs                                  ]8;id=428490;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py\data.py]8;;\:]8;id=518218;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py#69\69]8;;\
           INFO     Loading OSM POIs done (0.01 seconds)              ]8;id=379022;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py\data.py]8;;\:]8;id=77568;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py#69\69]8;;\
           INFO     Loading location mapping                          ]8;id=958758;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py\data.py]8;;\:]8;id=869106;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py#72\72]8;;\
[14:49:42] INFO     Loading location mapping done (4.57 seconds)      ]8;id=275658;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py\data.py]8;;\:]8;id=988419;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py#72\72]8;;\
           INFO     Loading OSM cycling                               ]8;id=987600;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py\data.py]8;;\:]8;id=683690;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py#82\82]8;;\
[14:49:44] INFO     Loading OSM cycling done (1.68 seconds)           ]8;id=948737;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py\data.py]8;;\:]8;id=671064;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py#82\82]8;;\
           INFO     Loading OSM driving                               ]8;id=13511;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py\data.py]8;;\:]8;id=446854;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py#82\82]8;;\
[14:49:45] INFO     Loading OSM driving done (0.53 seconds)           ]8;id=614350;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py\data.py]8;;\:]8;id=977386;file:///home/ppeter/repo/mcr-py/python/mcr_py/mcr/data.py#82\82]8;;\

In [4]:
all_files = list((mcr5_output_path / "walking").iterdir())
logging.info(len(all_files))

           INFO     5344                                         ]8;id=640795;file:///tmp/ipykernel_502392/3566842583.py\3566842583.py]8;;\:]8;id=591300;file:///tmp/ipykernel_502392/3566842583.py#2\2]8;;\

In [5]:
hex_test = mcr_py.mcr5.labels.read_labels_for_nodes(
    str(mcr5_output_path / "public_transport_0"),
    geo_data.pois.with_columns(pl.col("nearest_osm_node").alias("osm_node_id")).lazy(),
)
hex_test = mcr_py.minute_city.minute_city.add_pois_to_labels(
    hex_test.lazy(), geo_data.pois.lazy()
)
hex_test = hex_test.collect()


hex_test_comp = mcr_py.mcr5.labels.read_labels_for_nodes(
    str(pathlib.Path("../data/mcr5/cologne_20240423") / "walking"),
    geo_data.pois.with_columns(pl.col("nearest_osm_node").alias("osm_node_id")).lazy(),
)
hex_test_comp = mcr_py.minute_city.minute_city.add_pois_to_labels(
    hex_test_comp.lazy(), geo_data.pois.lazy()
)
hex_test_comp = hex_test_comp.collect()

In [25]:
poi_types = geo_data.pois.get_column("poi_type").unique().to_list()

In [27]:
hex_test.filter(pl.col("time") == pl.col("time").max().over("start_id_hex")).unique(
    ["start_id_hex", "poi_type", "time"] + poi_types
).sum()

shape: (1, 20)
┌────────────────┬───────────┬──────┬─────────────┬───┬────────────┬────────┬───────┬───────────┐
│ osm_node_id    ┆ time      ┆ cost ┆ n_transfers ┆ … ┆ Sustenance ┆ Health ┆ Banks ┆ Education │
│ ---            ┆ ---       ┆ ---  ┆ ---         ┆   ┆ ---        ┆ ---    ┆ ---   ┆ ---       │
│ i64            ┆ i64       ┆ i64  ┆ i64         ┆   ┆ i64        ┆ i64    ┆ i64   ┆ i64       │
╞════════════════╪═══════════╪══════╪═════════════╪═══╪════════════╪════════╪═══════╪═══════════╡
│ 25461864667853 ┆ 241103502 ┆ 0    ┆ 0           ┆ … ┆ 1219       ┆ 537    ┆ 431   ┆ 566       │
└────────────────┴───────────┴──────┴─────────────┴───┴────────────┴────────┴───────┴───────────┘

In [ ]:
hex_test_comp.join(hex_test, on=["start_id_hex", "poi_type", "osm_node_id"]).unique(
    ["start_id_hex", "poi_type", "osm_node_id", "time", "time_right"]
).filter((pl.col("time") - pl.col("time_right")).abs() > 180)

shape: (2_595, 37)
┌─────────────┬───────┬──────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ osm_node_id ┆ time  ┆ cost ┆ n_transfers ┆ … ┆ Parks_righ ┆ Banks_righ ┆ Sustenance ┆ Education_ │
│ ---         ┆ ---   ┆ ---  ┆ ---         ┆   ┆ t          ┆ t          ┆ _right     ┆ right      │
│ i64         ┆ i64   ┆ i64  ┆ i64         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│             ┆       ┆      ┆             ┆   ┆ i8         ┆ i8         ┆ i8         ┆ i8         │
╞═════════════╪═══════╪══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 286806461   ┆ 29287 ┆ 0    ┆ 0           ┆ … ┆ 1          ┆ 0          ┆ 0          ┆ 0          │
│ 2093837701  ┆ 29231 ┆ 0    ┆ 0           ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ 928177774   ┆ 31185 ┆ 0    ┆ 0           ┆ … ┆ 1          ┆ 0          ┆ 0          ┆ 0          │
│ 10591575910 ┆ 29440 ┆ 0    ┆ 0           ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ 1610945043  ┆ 31364 ┆ 0    ┆ 0           ┆ … ┆ 1          ┆ 0          ┆ 0          ┆ 0          │
│ …           ┆ …     ┆ …    ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 6584537420  ┆ 31232 ┆ 0    ┆ 0           ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ 8233800007  ┆ 29923 ┆ 0    ┆ 0           ┆ … ┆ 0          ┆ 0          ┆ 1          ┆ 0          │
│ 8507116653  ┆ 29598 ┆ 0    ┆ 0           ┆ … ┆ 0          ┆ 0          ┆ 1          ┆ 0          │
│ 5272539054  ┆ 29335 ┆ 0    ┆ 0           ┆ … ┆ 1          ┆ 0          ┆ 0          ┆ 0          │
│ 529647432   ┆ 29247 ┆ 0    ┆ 0           ┆ … ┆ 1          ┆ 0          ┆ 0          ┆ 0          │
└─────────────┴───────┴──────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [6]:
selected = hex_test.filter(pl.col("start_id_hex") == "881fa18ab5fffff")

In [7]:
poi_types = geo_data.pois.get_column("poi_type").unique().to_list()

In [8]:
import mcr_py.minute_city.profile

profiles = mcr_py.minute_city.profile.calculate_profile_for_group(selected, poi_types)

In [9]:
selected

shape: (69, 20)
┌─────────────┬───────┬──────┬─────────────┬───┬────────┬─────────┬────────────┬───────┐
│ osm_node_id ┆ time  ┆ cost ┆ n_transfers ┆ … ┆ Health ┆ Grocery ┆ Sustenance ┆ Banks │
│ ---         ┆ ---   ┆ ---  ┆ ---         ┆   ┆ ---    ┆ ---     ┆ ---        ┆ ---   │
│ i64         ┆ i64   ┆ i64  ┆ i64         ┆   ┆ i8     ┆ i8      ┆ i8         ┆ i8    │
╞═════════════╪═══════╪══════╪═════════════╪═══╪════════╪═════════╪════════════╪═══════╡
│ 3668330662  ┆ 30821 ┆ 0    ┆ 0           ┆ … ┆ 0      ┆ 0       ┆ 0          ┆ 0     │
│ 366310180   ┆ 31313 ┆ 0    ┆ 0           ┆ … ┆ 0      ┆ 0       ┆ 0          ┆ 0     │
│ 1458679913  ┆ 31265 ┆ 0    ┆ 0           ┆ … ┆ 1      ┆ 0       ┆ 0          ┆ 0     │
│ 7309941565  ┆ 30892 ┆ 0    ┆ 0           ┆ … ┆ 0      ┆ 0       ┆ 0          ┆ 1     │
│ 304146002   ┆ 30899 ┆ 0    ┆ 0           ┆ … ┆ 0      ┆ 0       ┆ 1          ┆ 0     │
│ …           ┆ …     ┆ …    ┆ …           ┆ … ┆ …      ┆ …       ┆ …          ┆ …     │
│ 11697309354 ┆ 30817 ┆ 0    ┆ 0           ┆ … ┆ 0      ┆ 0       ┆ 0          ┆ 0     │
│ 1727812560  ┆ 31169 ┆ 0    ┆ 0           ┆ … ┆ 0      ┆ 1       ┆ 0          ┆ 0     │
│ 446940874   ┆ 30745 ┆ 0    ┆ 0           ┆ … ┆ 0      ┆ 0       ┆ 0          ┆ 0     │
│ 266365220   ┆ 29844 ┆ 0    ┆ 0           ┆ … ┆ 0      ┆ 0       ┆ 1          ┆ 0     │
│ 6885637631  ┆ 31268 ┆ 0    ┆ 0           ┆ … ┆ 0      ┆ 0       ┆ 0          ┆ 0     │
└─────────────┴───────┴──────┴─────────────┴───┴────────┴─────────┴────────────┴───────┘

In [11]:
selected.group_by("poi_type").agg(pl.col("human_readable_time").min())

shape: (7, 2)
┌────────────┬─────────────────────┐
│ poi_type   ┆ human_readable_time │
│ ---        ┆ ---                 │
│ str        ┆ str                 │
╞════════════╪═════════════════════╡
│ Health     ┆ 08:01:15            │
│ Banks      ┆ 08:11:53            │
│ Shops      ┆ 08:06:11            │
│ Education  ┆ 08:10:19            │
│ Parks      ┆ 08:02:35            │
│ Sustenance ┆ 08:00:00            │
│ Grocery    ┆ 08:03:54            │
└────────────┴─────────────────────┘

In [4]:
geo_data.pois.group_by("poi_type").len()

shape: (7, 2)
┌────────────┬───────┐
│ poi_type   ┆ len   │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ Grocery    ┆ 2911  │
│ Health     ┆ 1821  │
│ Education  ┆ 545   │
│ Banks      ┆ 732   │
│ Parks      ┆ 16970 │
│ Shops      ┆ 5990  │
│ Sustenance ┆ 4004  │
└────────────┴───────┘